import { useState, type ReactNode } from 'react';
import { calculateBundle, calculateD2CProfitability, calculateInventoryPortfolio, calculateMarketplaceProfitability, calculateMarketingBudget, calculateRto, calculateRunway, calculateUnitEconomics, type BundleProduct, type D2CProfitInputs, type InventorySku, type MarketplaceProfitInputs, type MarketingChannel, type RtoInputs, type RunwayInputs, type UnitEconomicsInputs } from '@/lib/calculators';

type ToolId = 'rto-simulator' | 'unit-economics' | 'bundle-planner' | 'marketing-budget' | 'runway-planner' | 'inventory-planner' | 'ecommerce-platform-profit' | 'website-d2c-profit';
const money = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 2 });
const rupees = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 });
const num = new Intl.NumberFormat('en-IN', { maximumFractionDigits: 1 });
const integer = new Intl.NumberFormat('en-IN', { maximumFractionDigits: 0 });

function Field({ label, value, onChange, prefix, suffix, max, step = 1, hint }: { label: string; value: number; onChange: (n: number) => void; prefix?: string; suffix?: string; max?: number; step?: number; hint?: string }) {
  return <label className="calculator-field"><span className="calculator-label">{label}</span><span className="calculator-input-wrap">{prefix && <span className="input-affix input-prefix">{prefix}</span>}<input type="number" inputMode="decimal" min="0" max={max} step={step} value={value} onChange={e => onChange(Number(e.target.value))} />{suffix && <span className="input-affix input-suffix">{suffix}</span>}</span>{hint && <small>{hint}</small>}</label>;
}
function Metric({ label, value, detail, featured, negative }: { label: string; value: string; detail?: string; featured?: boolean; negative?: boolean }) {
  return <div className={`calculator-result${featured ? ' featured' : ''}${negative ? ' negative' : ''}`}><span>{label}</span><strong>{value}</strong>{detail && <small>{detail}</small>}</div>;
}
function Head({ n, title, action }: { n: string; title: string; action?: ReactNode }) { return <div className="calculator-section-heading"><div><span>{n}</span><h2>{title}</h2></div>{action}</div>; }
function Workspace({ inputs, results, note, children }: { inputs: ReactNode; results: ReactNode; note: string; children?: ReactNode }) { return <><div className="calculator-workspace"><section className="calculator-inputs">{inputs}</section><aside className="calculator-results" aria-live="polite">{results}<p className="calculator-note">{note}</p></aside></div>{children}</>; }
function Breakdown({ title, intro, rows, total }: { title: string; intro?: string; rows: [string, string][]; total?: [string, string] }) { return <section className="detail-panel"><div className="detail-heading"><h3>{title}</h3>{intro && <p>{intro}</p>}</div><dl className="breakdown-list">{rows.map(([k, v]) => <div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}{total && <div className="breakdown-total"><dt>{total[0]}</dt><dd>{total[1]}</dd></div>}</dl></section>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (checked: boolean) => void }) { return <label className="calculator-toggle"><input type="checkbox" checked={checked} onChange={event => onChange(event.target.checked)} /><span aria-hidden="true"></span><strong>{label}</strong></label>; }
function ProfitGroup({ kicker, title, rows }: { kicker: string; title: string; rows: { label: string; value: string; detail?: string; negative?: boolean }[] }) { return <section className="detail-panel profit-result-panel"><div className="detail-heading"><div><span className="detail-kicker">{kicker}</span><h3>{title}</h3></div></div><dl className="profit-result-list">{rows.map(row => <div key={row.label}><dt>{row.label}</dt><dd className={row.negative ? 'negative-cell' : undefined}>{row.value}</dd>{row.detail && <small>{row.detail}</small>}</div>)}</dl></section>; }

const rtoD: RtoInputs = { monthlyOrders: 2000, averageOrderValue: 1200, codPercent: 55, codRtoRate: 25, prepaidRtoRate: 3, forwardShipping: 65, reverseShipping: 120, packaging: 25, targetCodRtoRate: 15 };
function Rto() {
  const [x, setX] = useState(rtoD), r = calculateRto(x); const set = (k: keyof RtoInputs) => (v: number) => setX(o => ({ ...o, [k]: v }));
  const codRto = x.monthlyOrders * x.codPercent / 100 * x.codRtoRate / 100, preRto = x.monthlyOrders * r.prepaidPercent / 100 * x.prepaidRtoRate / 100;
  return <Workspace inputs={<><Head n="01" title="Your numbers" action={<button onClick={() => setX(rtoD)}>Reset</button>} /><p className="panel-intro">Adjust to match your store’s operational data.</p><div className="calculator-fields"><Field label="Monthly orders" value={x.monthlyOrders} onChange={set('monthlyOrders')} suffix="orders" /><Field label="Average order value" value={x.averageOrderValue} onChange={set('averageOrderValue')} prefix="₹" /><Field label="COD orders" value={x.codPercent} onChange={set('codPercent')} suffix="%" max={100} hint="Cash on Delivery share" /><div className="auto-field"><span>Prepaid orders</span><strong>{num.format(r.prepaidPercent)}%</strong><small>Calculated automatically</small></div><Field label="COD RTO rate" value={x.codRtoRate} onChange={set('codRtoRate')} suffix="%" max={100} /><Field label="Prepaid RTO rate" value={x.prepaidRtoRate} onChange={set('prepaidRtoRate')} suffix="%" max={100} /><Field label="Forward shipping" value={x.forwardShipping} onChange={set('forwardShipping')} prefix="₹" /><Field label="Reverse shipping" value={x.reverseShipping} onChange={set('reverseShipping')} prefix="₹" /><Field label="Packaging cost" value={x.packaging} onChange={set('packaging')} prefix="₹" /></div></>} results={<><Head n="02" title="Financial impact" /><div className="calculator-result-grid"><Metric label="Total RTO orders" value={integer.format(r.totalRtoOrders)} detail={`${integer.format(codRto)} COD + ${integer.format(preRto)} prepaid`} featured /><Metric label="Revenue lost" value={rupees.format(r.revenueLost)} detail="Orders that never converted" /><Metric label="Total RTO cost" value={rupees.format(r.totalRtoCost)} detail={`${num.format(x.monthlyOrders * x.averageOrderValue ? r.totalRtoCost / (x.monthlyOrders * x.averageOrderValue) * 100 : 0)}% of gross revenue`} /></div></>} note="Direct RTO cost includes forward shipping, reverse logistics, and packaging.">
    <div className="calculator-detail-grid"><Breakdown title="RTO cost breakdown" intro={`Direct costs from ${integer.format(r.totalRtoOrders)} returned orders.`} rows={[["Forward shipping wasted", rupees.format(r.totalRtoOrders * x.forwardShipping)], ["Reverse logistics cost", rupees.format(r.totalRtoOrders * x.reverseShipping)], ["Packaging wasted", rupees.format(r.totalRtoOrders * x.packaging)]]} total={["Total monthly RTO cost", rupees.format(r.totalRtoCost)]} /><section className="detail-panel savings-panel"><div className="detail-heading"><span className="detail-kicker">Savings simulator</span><h3>What if COD RTO dropped?</h3></div><label className="calculator-field calculator-slider-field"><span className="calculator-label">Target COD RTO rate</span><div className="slider-value"><strong>{num.format(Math.min(x.targetCodRtoRate, x.codRtoRate))}%</strong><span>Current: {num.format(x.codRtoRate)}%</span></div><input type="range" min="0" max={Math.max(1, x.codRtoRate)} step="0.5" value={Math.min(x.targetCodRtoRate, x.codRtoRate)} onChange={e => set('targetCodRtoRate')(Number(e.target.value))} /></label><div className="savings-grid"><Metric label="RTO cost saved" value={rupees.format(r.rtoCostSaved)} detail="per month" /><Metric label="Orders recovered" value={integer.format(r.ordersSaved)} detail="orders/month" /><Metric label="Revenue recovered" value={rupees.format(r.revenueSaved)} detail="per month" /></div></section></div>
  </Workspace>;
}

const unitD: UnitEconomicsInputs = { sellingPrice: 1499, discountPercent: 20, cogs: 350, packaging: 25, shipping: 65, gatewayFeePercent: 2, gstPercent: 12, rtoRate: 15, reverseLogistics: 120, monthlyAdSpend: 200000, monthlyOrders: 400 };
function Unit() {
  const [x, setX] = useState(unitD), r = calculateUnitEconomics(x); const set = (k: keyof UnitEconomicsInputs) => (v: number) => setX(o => ({ ...o, [k]: v }));
  const costs: [string, number][] = [['COGS', x.cogs], ['Shipping', x.shipping], ['Packaging', x.packaging], ['Gateway fee', r.gatewayFee], ['GST', r.gst], ['CAC', r.cac], ['RTO drag', r.rtoDrag], [r.contributionMargin >= 0 ? 'Profit' : 'Loss', r.contributionMargin]];
  return <Workspace inputs={<><Head n="01" title="Your numbers" action={<button onClick={() => setX(unitD)}>Reset</button>} /><p className="panel-intro">All fields update results in real time.</p><div className="calculator-fields"><Field label="Selling price" value={x.sellingPrice} onChange={set('sellingPrice')} prefix="₹" hint="MRP before discount" /><Field label="Average discount" value={x.discountPercent} onChange={set('discountPercent')} suffix="%" max={100} /><Field label="COGS / unit" value={x.cogs} onChange={set('cogs')} prefix="₹" /><Field label="Packaging" value={x.packaging} onChange={set('packaging')} prefix="₹" /><Field label="Shipping" value={x.shipping} onChange={set('shipping')} prefix="₹" /><Field label="Gateway fee" value={x.gatewayFeePercent} onChange={set('gatewayFeePercent')} suffix="%" max={100} step={.1} /><Field label="GST" value={x.gstPercent} onChange={set('gstPercent')} suffix="%" max={100} /><Field label="RTO rate" value={x.rtoRate} onChange={set('rtoRate')} suffix="%" max={100} /><Field label="Reverse logistics" value={x.reverseLogistics} onChange={set('reverseLogistics')} prefix="₹" /><Field label="Monthly ad spend" value={x.monthlyAdSpend} onChange={set('monthlyAdSpend')} prefix="₹" /><Field label="Monthly orders" value={x.monthlyOrders} onChange={set('monthlyOrders')} suffix="orders" /></div></>} results={<><Head n="02" title="Per-order economics" /><div className="calculator-result-grid compact-metrics"><Metric label="Contribution margin" value={money.format(r.contributionMargin)} detail={`${num.format(r.contributionMarginPercent)}%`} featured negative={r.contributionMargin < 0} /><Metric label="Net selling price" value={money.format(r.netSellingPrice)} detail={`After ${num.format(x.discountPercent)}% discount`} /><Metric label="Gross margin" value={money.format(r.grossMargin)} detail={`${num.format(r.grossMarginPercent)}%`} /><Metric label="CAC" value={money.format(r.cac)} /><Metric label="RTO drag / order" value={money.format(r.rtoDrag)} /><Metric label="Break-even orders" value={r.breakEvenOrders === null ? 'Not reachable' : integer.format(r.breakEvenOrders)} /></div></>} note="GST is modelled on discounted selling price. Contribution margin includes CAC and excludes fixed overheads.">
    <section className="monthly-metrics"><Metric label="Monthly revenue" value={money.format(r.monthlyRevenue)} detail={`${integer.format(x.monthlyOrders)} orders`} /><Metric label="Monthly total cost" value={money.format(r.monthlyTotalCost)} detail={`${money.format(r.totalCostPerOrder)} / order`} /><Metric label="Monthly profit / loss" value={money.format(r.monthlyProfit)} detail={r.monthlyProfit >= 0 ? 'Profit' : 'Loss'} negative={r.monthlyProfit < 0} /></section><section className="detail-panel wide-panel"><div className="detail-heading"><h3>Per-order cost breakdown</h3><p>Where every rupee of your {money.format(r.netSellingPrice)} selling price goes.</p></div><dl className="breakdown-list breakdown-columns">{costs.map(([k, v]) => <div key={k}><dt>{k}</dt><dd>{money.format(v)}</dd></div>)}<div className="breakdown-total"><dt>Total cost</dt><dd>{money.format(r.totalCostPerOrder)}</dd></div></dl></section>
  </Workspace>;
}

const productD: BundleProduct[] = [{ id: 1, name: 'Hero Product', price: 799, cogs: 180 }, { id: 2, name: 'Daily Essential', price: 599, cogs: 140 }, { id: 3, name: 'Add-on Product', price: 499, cogs: 110 }];
function Bundle() {
  const [products, setProducts] = useState(productD), [discount, setDiscount] = useState(15), [uplift, setUplift] = useState(20), [orders, setOrders] = useState(500), [adoption, setAdoption] = useState(60); const r = calculateBundle(products, discount, uplift, orders, adoption);
  const edit = (id: number, k: keyof BundleProduct, v: string | number) => setProducts(a => a.map(p => p.id === id ? { ...p, [k]: v } : p)); const reset = () => { setProducts(productD); setDiscount(15); setUplift(20); setOrders(500); setAdoption(60); };
  return <Workspace inputs={<><Head n="01" title="Bundle products" action={<><button onClick={reset}>Reset</button><button disabled={products.length >= 5} onClick={() => setProducts(a => [...a, { id: Date.now(), name: `Product ${a.length + 1}`, price: 399, cogs: 100 }])}>Add product</button></>} /><p className="panel-intro">Add 2–5 products to your bundle.</p><div className="product-list">{products.map(p => <div className="product-row" key={p.id}><label><span>Product name</span><input value={p.name} onChange={e => edit(p.id, 'name', e.target.value)} /></label><Field label="Selling price" value={p.price} onChange={v => edit(p.id, 'price', v)} prefix="₹" /><Field label="COGS" value={p.cogs} onChange={v => edit(p.id, 'cogs', v)} prefix="₹" /><div className="product-margin"><span>Margin</span><strong>{num.format(p.price ? (p.price - p.cogs) / p.price * 100 : 0)}%</strong></div>{products.length > 2 && <button className="remove-row" onClick={() => setProducts(a => a.filter(i => i.id !== p.id))}>×</button>}</div>)}</div><div className="subsection-heading"><h3>Bundle settings</h3></div><div className="calculator-fields"><Field label="Bundle discount" value={discount} onChange={setDiscount} suffix="%" max={100} /><Field label="Conversion uplift" value={uplift} onChange={setUplift} suffix="%" /><Field label="Current monthly orders" value={orders} onChange={setOrders} suffix="orders" /><Field label="Bundle adoption" value={adoption} onChange={setAdoption} suffix="%" max={100} hint="Orders expected to choose bundle" /></div></>} results={<><Head n="02" title="Bundle breakdown" /><Breakdown title="" rows={[["Bundle MRP (sum)", money.format(r.listValue)], [`Discount (${num.format(discount)}%)`, `−${money.format(r.discountAmount)}`], ["Bundle selling price", money.format(r.bundleSellingPrice)], ["Total COGS", money.format(r.totalCogs)]]} total={["Bundle margin", `${money.format(r.bundleMargin)} · ${num.format(r.bundleMarginPercent)}%`]} /><div className="calculator-result-grid"><Metric label="Projected AOV" value={money.format(r.projectedAov)} detail={`+${num.format(r.aovUpliftPercent)}% uplift`} featured /><Metric label="Current AOV" value={money.format(r.currentAov)} /><Metric label="Projected orders" value={integer.format(r.projectedOrders)} /></div></>} note="Projected AOV blends single-item and bundle orders using bundle adoption.">
    <section className="monthly-metrics"><Metric label="Current monthly revenue" value={money.format(r.currentRevenue)} /><Metric label="Projected monthly revenue" value={money.format(r.projectedRevenue)} /><Metric label="Revenue uplift" value={money.format(r.revenueUplift)} detail={`+${num.format(r.revenueUpliftPercent)}%`} /></section><section className="detail-panel wide-panel"><div className="detail-heading"><h3>AOV comparison</h3></div><div className="comparison-bars"><div><span>Before bundles</span><i style={{ width: `${r.projectedAov ? r.currentAov / r.projectedAov * 100 : 0}%` }}></i><strong>{money.format(r.currentAov)}</strong></div><div><span>After bundles</span><i style={{ width: '100%' }}></i><strong>{money.format(r.projectedAov)}</strong></div></div></section>
  </Workspace>;
}

const channelD: MarketingChannel[] = [{ id: 'meta', name: 'Meta Ads', allocation: 40, roas: 3.5 }, { id: 'google', name: 'Google Ads', allocation: 30, roas: 4 }, { id: 'email', name: 'Email / SMS', allocation: 15, roas: 8 }, { id: 'influencer', name: 'Influencer', allocation: 10, roas: 2.5 }, { id: 'other', name: 'Other', allocation: 5, roas: 2 }];
function Marketing() {
  const [budget, setBudget] = useState(500000), [aov, setAov] = useState(1200), [channels, setChannels] = useState(channelD); const r = calculateMarketingBudget(budget, aov, channels); const edit = (id: string, k: 'allocation' | 'roas', v: number) => setChannels(a => a.map(c => c.id === id ? { ...c, [k]: v } : c));
  return <Workspace inputs={<><Head n="01" title="Budget overview" action={<button onClick={() => { setBudget(500000); setAov(1200); setChannels(channelD); }}>Reset</button>} /><div className="calculator-fields"><Field label="Total monthly budget" value={budget} onChange={setBudget} prefix="₹" /><Field label="Average order value" value={aov} onChange={setAov} prefix="₹" /></div><div className="subsection-heading allocation-heading"><h3>Channel allocation</h3><span className={r.totalAllocation === 100 ? 'valid' : 'invalid'}>{num.format(r.totalAllocation)}% allocated</span></div><div className="channel-list">{r.channels.map(c => <div className="channel-row" key={c.id}><div><strong>{c.name}</strong><span>{rupees.format(c.spend)}</span></div><Field label="Budget allocation" value={c.allocation} onChange={v => edit(c.id, 'allocation', v)} suffix="%" max={100} /><Field label="Expected ROAS" value={c.roas} onChange={v => edit(c.id, 'roas', v)} suffix="×" step={.1} /></div>)}</div></>} results={<><Head n="02" title="Blended forecast" /><div className="calculator-result-grid"><Metric label="Projected revenue" value={rupees.format(r.expectedRevenue)} detail={`${integer.format(r.expectedOrders)} orders`} featured /><Metric label="Blended ROAS" value={`${num.format(r.blendedRoas)}×`} /><Metric label="Blended CPA" value={rupees.format(r.blendedCpa)} /><Metric label="Total spend" value={rupees.format(r.totalSpend)} /></div></>} note={r.totalAllocation === 100 ? 'Allocation is balanced. Revenue is spend × expected ROAS per channel.' : `Allocations total ${num.format(r.totalAllocation)}%. Bring them to 100%.`}>
    <section className="detail-panel wide-panel"><div className="detail-heading"><h3>Budget split</h3></div><div className="budget-bar">{r.channels.map(c => <i key={c.id} style={{ width: `${r.totalAllocation ? c.allocation / r.totalAllocation * 100 : 0}%` }}></i>)}</div><div className="budget-legend">{r.channels.map(c => <span key={c.id}>{c.name} ({num.format(c.allocation)}%)</span>)}</div></section><MetricsTable rows={r.channels.map(c => [c.name, rupees.format(c.spend), rupees.format(c.revenue), integer.format(c.orders), rupees.format(c.cpa)])} total={['Total', rupees.format(r.totalSpend), rupees.format(r.expectedRevenue), integer.format(r.expectedOrders), rupees.format(r.blendedCpa)]} />
  </Workspace>;
}
function MetricsTable({ rows, total }: { rows: string[][]; total?: string[] }) { return <section className="detail-panel wide-panel table-panel"><div className="detail-heading"><h3>Channel metrics</h3></div><div className="table-scroll"><table><thead><tr><th>Channel</th><th>Spend</th><th>Revenue</th><th>Orders</th><th>CPA</th></tr></thead><tbody>{rows.map(r => <tr key={r[0]}>{r.map((v, i) => i ? <td key={i}>{v}</td> : <th key={i}>{v}</th>)}</tr>)}{total && <tr className="table-total">{total.map((v, i) => i ? <td key={i}>{v}</td> : <th key={i}>{v}</th>)}</tr>}</tbody></table></div></section>; }

const runwayD: RunwayInputs = { cash: 2500000, monthlyRevenue: 800000, monthlyGrowthPercent: 8, fixedCosts: 350000, variableCostPercent: 45, marketingSpend: 200000 };
function Runway() {
  const [x, setX] = useState(runwayD), r = calculateRunway(x); const set = (k: keyof RunwayInputs) => (v: number) => setX(o => ({ ...o, [k]: v })); const max = Math.max(1, ...r.projection.map(m => Math.abs(m.cashBalance)));
  return <Workspace inputs={<><Head n="01" title="Your numbers" action={<button onClick={() => setX(runwayD)}>Reset</button>} /><p className="panel-intro">All fields update the 24-month projection.</p><div className="calculator-fields"><Field label="Current cash balance" value={x.cash} onChange={set('cash')} prefix="₹" /><Field label="Monthly revenue" value={x.monthlyRevenue} onChange={set('monthlyRevenue')} prefix="₹" /><Field label="MoM growth" value={x.monthlyGrowthPercent} onChange={set('monthlyGrowthPercent')} suffix="%" step={.5} /><Field label="Fixed monthly costs" value={x.fixedCosts} onChange={set('fixedCosts')} prefix="₹" /><Field label="Variable costs" value={x.variableCostPercent} onChange={set('variableCostPercent')} suffix="% of rev" max={100} /><Field label="Monthly marketing spend" value={x.marketingSpend} onChange={set('marketingSpend')} prefix="₹" /></div></>} results={<><Head n="02" title="Runway forecast" /><div className="calculator-result-grid"><Metric label="Runway" value={r.runwayMonths === null ? '24+ months' : `${r.runwayMonths} months`} detail={r.runwayMonths === null ? 'Healthy' : 'Until cash reaches zero'} featured /><Metric label="Monthly burn" value={rupees.format(r.monthlyBurn)} /><Metric label="Break-even month" value={r.breakEvenMonth ? `Month ${r.breakEvenMonth}` : 'Beyond 24 months'} /></div></>} note="Revenue compounds monthly; variable costs scale with it. Fixed costs and marketing stay constant.">
    <section className="detail-panel wide-panel"><div className="detail-heading"><h3>Cash balance projection</h3><p>Green = positive, red = negative.</p></div><div className="runway-chart">{r.projection.map(m => <div key={m.month} title={`Month ${m.month}: ${rupees.format(m.cashBalance)}`}><i className={m.cashBalance < 0 ? 'negative' : ''} style={{ height: `${Math.max(3, Math.abs(m.cashBalance) / max * 100)}%` }}></i><span>{[1, 12, 24].includes(m.month) ? `M${m.month}` : ''}</span></div>)}</div></section><section className="detail-panel wide-panel table-panel"><div className="detail-heading"><h3>Month-by-month projection</h3></div><div className="table-scroll"><table><thead><tr><th>Month</th><th>Revenue</th><th>Costs</th><th>Net flow</th><th>Cash balance</th></tr></thead><tbody>{r.projection.map(m => <tr key={m.month}><th>Month {m.month}</th><td>{rupees.format(m.revenue)}</td><td>{rupees.format(m.costs)}</td><td className={m.netFlow < 0 ? 'negative-cell' : 'positive-cell'}>{m.netFlow >= 0 ? '+' : ''}{rupees.format(m.netFlow)}</td><td>{rupees.format(m.cashBalance)}</td></tr>)}</tbody></table></div></section>
  </Workspace>;
}

const profitCommon = { grossSellingPrice: 1699, salesGstRate: 3, tdsRate: .1, tcsRate: .5, productCost: 500, roas: 2.3, targetProfitMargin: 10, returnRate: 10, rtoRate: 5, returnProcessingCost: 0, returnedProductLossPercent: 0, otherCostPerOrder: 0 };
const marketplaceD: MarketplaceProfitInputs = { ...profitCommon, platformCommission: 35, gstOnCommission: 18, regularLogisticsCost: 0, returnOutwardCost: 30, returnInwardCost: 30, rtoCost: 0, commissionRefunded: true };
const d2cD: D2CProfitInputs = { ...profitCommon, paymentGatewayRate: 2, gstOnGatewayFee: 18, forwardDeliveryCost: 80, returnReverseCost: 80, rtoReverseCost: 80, gatewayFeeRefunded: false };

function ProfitCalculator({ mode }: { mode: 'marketplace' | 'd2c' }) {
  const defaults = mode === 'marketplace' ? marketplaceD : d2cD;
  const [x, setX] = useState<MarketplaceProfitInputs | D2CProfitInputs>(defaults);
  const set = (key: string) => (value: number | boolean) => setX(current => ({ ...current, [key]: value }));
  const r = mode === 'marketplace' ? calculateMarketplaceProfitability(x as MarketplaceProfitInputs) : calculateD2CProfitability(x as D2CProfitInputs);
  const channel = mode === 'marketplace' ? x as MarketplaceProfitInputs : x as D2CProfitInputs;
  const feeLabel = mode === 'marketplace' ? 'Platform Commission' : 'Gateway Fee';
  const feeGstLabel = mode === 'marketplace' ? 'GST on Commission' : 'GST on Gateway Fee';
  const pct = (value: number) => `${value.toFixed(2)}%`;
  const decimal = (value: number | null) => value === null ? 'Not reachable' : value.toFixed(2);
  const price = (value: number | null) => value === null ? 'Not reachable' : money.format(value);
  const feeFormula = mode === 'marketplace'
    ? `${money.format(x.grossSellingPrice)} × ${(channel as MarketplaceProfitInputs).platformCommission}%${(channel as MarketplaceProfitInputs).commissionRefunded ? ` × ${pct(r.successfulOrderRate)} success` : ''}`
    : `${money.format(x.grossSellingPrice)} × ${(channel as D2CProfitInputs).paymentGatewayRate}%${(channel as D2CProfitInputs).gatewayFeeRefunded ? ` × ${pct(r.successfulOrderRate)} success` : ''}`;
  const logisticsFormula = mode === 'marketplace'
    ? `${money.format((channel as MarketplaceProfitInputs).regularLogisticsCost)} + ${x.returnRate}%×(${money.format((channel as MarketplaceProfitInputs).returnOutwardCost)}+${money.format((channel as MarketplaceProfitInputs).returnInwardCost)}) + ${x.rtoRate}%×${money.format((channel as MarketplaceProfitInputs).rtoCost)}`
    : `${money.format((channel as D2CProfitInputs).forwardDeliveryCost)} + ${x.returnRate}%×${money.format((channel as D2CProfitInputs).returnReverseCost)} + ${x.rtoRate}%×${money.format((channel as D2CProfitInputs).rtoReverseCost)}`;
  const pricingWarning = r.pricingIsImpractical ? 'The target price is mathematically possible but may be commercially impractical because variable costs consume nearly all retained revenue.' : undefined;

  return <Workspace inputs={<>
    <Head n="01" title="Profit inputs" action={<button onClick={() => setX(defaults)}>Reset</button>} />
    <div className="subsection-heading profit-input-heading"><h3>Common inputs</h3></div>
    <div className="calculator-fields">
      <Field label="Gross selling price" value={x.grossSellingPrice} onChange={set('grossSellingPrice')} prefix="₹" />
      <Field label="Sales GST rate" value={x.salesGstRate} onChange={set('salesGstRate')} suffix="%" max={100} step={.1} />
      <Field label="TDS rate" value={x.tdsRate} onChange={set('tdsRate')} suffix="%" max={100} step={.1} />
      <Field label="TCS rate" value={x.tcsRate} onChange={set('tcsRate')} suffix="%" max={100} step={.1} />
      <Field label="Product cost (COGS)" value={x.productCost} onChange={set('productCost')} prefix="₹" />
      <Field label="ROAS (reported)" value={x.roas} onChange={set('roas')} step={.1} />
      <Field label="Target profit margin" value={x.targetProfitMargin} onChange={set('targetProfitMargin')} suffix="%" max={100} step={.1} />
      <Field label="Return rate" value={x.returnRate} onChange={set('returnRate')} suffix="%" max={100} step={.1} />
      <Field label="RTO rate" value={x.rtoRate} onChange={set('rtoRate')} suffix="%" max={100} step={.1} />
      <Field label="Return processing cost" value={x.returnProcessingCost} onChange={set('returnProcessingCost')} prefix="₹" />
      <Field label="Returned product loss" value={x.returnedProductLossPercent} onChange={set('returnedProductLossPercent')} suffix="%" max={100} step={.1} />
      <Field label="Other cost per order" value={x.otherCostPerOrder} onChange={set('otherCostPerOrder')} prefix="₹" />
    </div>
    <div className="subsection-heading"><h3>{mode === 'marketplace' ? 'Platform inputs' : 'Website / gateway inputs'}</h3></div>
    {mode === 'marketplace' ? <div className="calculator-fields">
      <Field label="Platform commission" value={(channel as MarketplaceProfitInputs).platformCommission} onChange={set('platformCommission')} suffix="%" max={100} step={.1} />
      <Field label="GST on commission" value={(channel as MarketplaceProfitInputs).gstOnCommission} onChange={set('gstOnCommission')} suffix="%" max={100} step={.1} />
      <Field label="Regular logistics cost" value={(channel as MarketplaceProfitInputs).regularLogisticsCost} onChange={set('regularLogisticsCost')} prefix="₹" />
      <Field label="Return outward cost" value={(channel as MarketplaceProfitInputs).returnOutwardCost} onChange={set('returnOutwardCost')} prefix="₹" />
      <Field label="Return inward cost" value={(channel as MarketplaceProfitInputs).returnInwardCost} onChange={set('returnInwardCost')} prefix="₹" />
      <Field label="RTO cost" value={(channel as MarketplaceProfitInputs).rtoCost} onChange={set('rtoCost')} prefix="₹" />
    </div> : <div className="calculator-fields">
      <Field label="Payment gateway rate" value={(channel as D2CProfitInputs).paymentGatewayRate} onChange={set('paymentGatewayRate')} suffix="%" max={100} step={.1} />
      <Field label="GST on gateway fee" value={(channel as D2CProfitInputs).gstOnGatewayFee} onChange={set('gstOnGatewayFee')} suffix="%" max={100} step={.1} />
      <Field label="Forward delivery cost" value={(channel as D2CProfitInputs).forwardDeliveryCost} onChange={set('forwardDeliveryCost')} prefix="₹" />
      <Field label="Return reverse cost" value={(channel as D2CProfitInputs).returnReverseCost} onChange={set('returnReverseCost')} prefix="₹" />
      <Field label="RTO reverse cost" value={(channel as D2CProfitInputs).rtoReverseCost} onChange={set('rtoReverseCost')} prefix="₹" />
    </div>}
    <Toggle label={mode === 'marketplace' ? 'Commission refunded on returns / RTO' : 'Gateway fee refunded on returns'} checked={mode === 'marketplace' ? (channel as MarketplaceProfitInputs).commissionRefunded : (channel as D2CProfitInputs).gatewayFeeRefunded} onChange={set(mode === 'marketplace' ? 'commissionRefunded' : 'gatewayFeeRefunded')} />
  </>} results={<>
    <Head n="02" title="Profit snapshot" />
    <div className="calculator-result-grid compact-metrics">
      <Metric label="Expected profit" value={money.format(r.expectedProfit)} detail={`${pct(r.profitMargin)} margin`} featured negative={r.expectedProfit < 0} />
      <Metric label="Expected payout" value={money.format(r.expectedPayout)} />
      <Metric label="Price for target profit" value={price(r.targetSellingPrice)} detail={`${x.targetProfitMargin}% target margin`} />
      <Metric label="Break-even ROAS" value={decimal(r.breakEvenRoas)} />
    </div>
  </>} note="TDS, TCS and GST on the platform or gateway fee are shown in payout as recoverable deductions and are not counted as profit expenses.">
    <div className="profit-result-sections">
      <ProfitGroup kicker="A" title="Revenue" rows={[
        { label: 'Gross selling price', value: money.format(x.grossSellingPrice) },
        { label: 'Successful order rate', value: pct(r.successfulOrderRate), detail: `1 − ${x.returnRate}% − ${x.rtoRate}% = ${pct(r.successfulOrderRate)}` },
        { label: 'Expected gross revenue', value: money.format(r.expectedGrossRevenue), detail: `${money.format(x.grossSellingPrice)} × ${pct(r.successfulOrderRate)}` },
        { label: 'Expected taxable revenue', value: money.format(r.expectedTaxableRevenue), detail: `${money.format(r.expectedGrossRevenue)} ÷ (1 + ${x.salesGstRate}%)` },
        { label: 'Output GST', value: money.format(r.outputGst), detail: `${money.format(r.expectedGrossRevenue)} − ${money.format(r.expectedTaxableRevenue)}` },
      ]} />
      <ProfitGroup kicker="B" title="Deductions" rows={[
        { label: 'TDS (recoverable)', value: money.format(r.tds), detail: `${money.format(r.expectedTaxableRevenue)} × ${x.tdsRate}%` },
        { label: 'TCS (recoverable)', value: money.format(r.tcs), detail: `${money.format(r.expectedTaxableRevenue)} × ${x.tcsRate}%` },
        { label: feeLabel, value: money.format(r.fee), detail: feeFormula },
        { label: feeGstLabel, value: money.format(r.feeGst), detail: `${money.format(r.fee)} × ${mode === 'marketplace' ? (channel as MarketplaceProfitInputs).gstOnCommission : (channel as D2CProfitInputs).gstOnGatewayFee}%` },
        { label: 'Expected logistics', value: money.format(r.expectedLogistics), detail: logisticsFormula },
        { label: 'Expected payout', value: money.format(r.expectedPayout), detail: `Gross revenue − recoverable deductions − ${feeLabel.toLowerCase()} − fee GST − logistics` },
      ]} />
      <ProfitGroup kicker="C" title="Profitability" rows={[
        { label: 'Reported ROAS', value: x.roas.toFixed(2) },
        { label: 'Net ROAS after returns', value: r.netRoasAfterReturns.toFixed(2), detail: `${x.roas} × ${pct(r.successfulOrderRate)}` },
        { label: 'Ad cost per order', value: money.format(r.adCostPerOrder), detail: x.roas > 0 ? `${money.format(x.grossSellingPrice)} ÷ ${x.roas}` : 'Enter a ROAS above zero' },
        { label: 'Expected product cost', value: money.format(r.expectedProductCost), detail: `${money.format(x.productCost)} × ${pct(r.successfulOrderRate)}` },
        { label: 'Returned product loss', value: money.format(r.returnedProductLoss), detail: `${money.format(x.productCost)} × ${x.returnRate}% × ${x.returnedProductLossPercent}% loss` },
        { label: 'Expected profit', value: money.format(r.expectedProfit), detail: `Taxable revenue − ${feeLabel.toLowerCase()} − logistics − ads − product and return costs`, negative: r.expectedProfit < 0 },
        { label: 'Profit margin', value: pct(r.profitMargin), detail: `${money.format(r.expectedProfit)} ÷ ${money.format(r.expectedTaxableRevenue)} × 100`, negative: r.profitMargin < 0 },
      ]} />
      <ProfitGroup kicker="D" title="Pricing recommendation" rows={[
        { label: 'Break-even selling price', value: price(r.breakEvenSellingPrice), detail: 'Fixed costs ÷ retained revenue coefficient at current ROAS' },
        { label: `Price for ${x.targetProfitMargin}% profit`, value: price(r.targetSellingPrice), detail: pricingWarning ?? 'Fixed costs ÷ retained revenue coefficient after target profit' },
        { label: 'Required price increase', value: price(r.requiredPriceIncrease), detail: r.targetSellingPrice === null ? 'Target is not reachable with the current variable-cost rates' : `${money.format(r.targetSellingPrice)} − ${money.format(x.grossSellingPrice)}` },
        { label: 'Required increase %', value: r.requiredIncreasePercent === null ? 'Not reachable' : pct(r.requiredIncreasePercent), detail: r.requiredPriceIncrease === null ? undefined : `${money.format(r.requiredPriceIncrease)} ÷ ${money.format(x.grossSellingPrice)} × 100` },
        { label: 'Break-even ROAS', value: decimal(r.breakEvenRoas), detail: r.breakEvenRoas === null ? 'No affordable ad cost remains' : `${money.format(x.grossSellingPrice)} ÷ max affordable ad cost (${money.format(r.maxAffordableAdCost)})` },
      ]} />
    </div>
  </Workspace>;
}

const skuD: InventorySku[] = [{ id: 1, name: 'Hero SKU', currentStock: 500, dailySales: 14, leadTimeDays: 20, safetyDays: 7, costPerUnit: 180 }, { id: 2, name: 'Core SKU', currentStock: 320, dailySales: 9, leadTimeDays: 21, safetyDays: 7, costPerUnit: 140 }, { id: 3, name: 'Fast-moving SKU', currentStock: 80, dailySales: 22, leadTimeDays: 20, safetyDays: 6, costPerUnit: 110 }];
function Inventory() {
  const [skus, setSkus] = useState(skuD), r = calculateInventoryPortfolio(skus); const edit = (id: number, k: keyof InventorySku, v: string | number) => setSkus(a => a.map(s => s.id === id ? { ...s, [k]: v } : s));
  return <><section className="inventory-summary"><Metric label="Total SKUs" value={String(skus.length)} /><Metric label="Working capital" value={rupees.format(r.workingCapital)} detail="Locked in inventory" /><Metric label="Critical SKUs" value={String(r.criticalSkus)} /><Metric label="Reorder now" value={String(r.reorderNow)} /></section><section className="sku-planner"><Head n="01" title="Your SKUs" action={<><button onClick={() => setSkus(skuD)}>Reset</button><button disabled={skus.length >= 8} onClick={() => setSkus(a => [...a, { id: Date.now(), name: `SKU ${a.length + 1}`, currentStock: 100, dailySales: 5, leadTimeDays: 14, safetyDays: 7, costPerUnit: 100 }])}>Add SKU</button></>} /><div className="sku-list">{r.items.map(s => <article className="sku-card" key={s.id}><div className="sku-card-heading"><label><span>SKU name</span><input value={s.name} onChange={e => edit(s.id, 'name', e.target.value)} /></label><span className={`stock-status ${s.status}`}>{s.status === 'healthy' ? 'Healthy' : s.status === 'critical' ? 'Critical' : 'Reorder'}</span>{skus.length > 1 && <button className="remove-row" onClick={() => setSkus(a => a.filter(i => i.id !== s.id))}>×</button>}</div><div className="calculator-fields sku-fields"><Field label="Current stock" value={s.currentStock} onChange={v => edit(s.id, 'currentStock', v)} suffix="units" /><Field label="Daily sales" value={s.dailySales} onChange={v => edit(s.id, 'dailySales', v)} suffix="units" /><Field label="Lead time" value={s.leadTimeDays} onChange={v => edit(s.id, 'leadTimeDays', v)} suffix="days" /><Field label="Safety stock" value={s.safetyDays} onChange={v => edit(s.id, 'safetyDays', v)} suffix="days" /><Field label="Cost per unit" value={s.costPerUnit} onChange={v => edit(s.id, 'costPerUnit', v)} prefix="₹" /></div><div className="sku-metrics"><Metric label="Reorder point" value={`${integer.format(Math.ceil(s.reorderPoint))} units`} /><Metric label="Days to stockout" value={s.daysToStockout === null ? '—' : `${num.format(s.daysToStockout)} days`} /><Metric label="Order qty suggested" value={`${integer.format(Math.ceil(s.suggestedOrderQty))} units`} detail="30-day replenishment" /><Metric label="Capital locked" value={rupees.format(s.capitalLocked)} /></div><div className="stock-progress"><span>Stock vs reorder point</span><strong>{integer.format(s.currentStock)} / {integer.format(s.reorderPoint)}</strong><i><b style={{ width: `${Math.min(100, s.reorderPoint ? s.currentStock / s.reorderPoint * 100 : 100)}%` }}></b></i></div></article>)}</div></section></>;
}

export function CalculatorApp({ toolId }: { toolId: ToolId }) { switch (toolId) { case 'rto-simulator': return <Rto />; case 'unit-economics': return <Unit />; case 'bundle-planner': return <Bundle />; case 'marketing-budget': return <Marketing />; case 'runway-planner': return <Runway />; case 'inventory-planner': return <Inventory />; case 'ecommerce-platform-profit': return <ProfitCalculator mode="marketplace" />; case 'website-d2c-profit': return <ProfitCalculator mode="d2c" />; } }
